### Get Tidak Bagus
POST http://localhost:8000/predict
Content-Type: application/json

{
    "nilai": 95,
    "homepage": 0,
    "modul_perkuliahan": 1,
    "forum": 0,
    "tugas": 1,
    "kuis": 0,
    "uts": 1,
    "uas": 0
}


### Get Bagus
POST http://localhost:8000/predict
Content-Type: application/json

{
    "nilai": 80,
    "homepage": 1,
    "modul_perkuliahan": 0,
    "forum": 0,
    "tugas": 0,
    "kuis": 0,
    "uts": 0,
    "uas": 0
}